# Generated by Django 4.0.5 on 2022-07-28 18:22

import ckeditor.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Banner',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=55, verbose_name='Banner nomi')),
                ('name_en', models.CharField(max_length=55, null=True, verbose_name='Banner nomi')),
                ('name_ru', models.CharField(max_length=55, null=True, verbose_name='Banner nomi')),
                ('name_uz', models.CharField(max_length=55, null=True, verbose_name='Banner nomi')),
                ('image', models.ImageField(upload_to='category_images', verbose_name='Banner rasmi')),
                ('description', models.TextField(verbose_name='Banner teksti')),
                ('description_en', models.TextField(null=True, verbose_name='Banner teksti')),
                ('description_ru', models.TextField(null=True, verbose_name='Banner teksti')),
                ('description_uz', models.TextField(null=True, verbose_name='Banner teksti')),
                ('banner_type', models.CharField(choices=[('Big', 'big'), ('Medium', 'medium'), ('Small', 'small')], max_length=25, verbose_name='Banner turi')),
            ],
            options={
                'verbose_name': 'Banner',
                'verbose_name_plural': 'Bannerlar',
            },
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=55, verbose_name='Kategoriya nomi')),
                ('name_en', models.CharField(max_length=55, null=True, verbose_name='Kategoriya nomi')),
                ('name_ru', models.CharField(max_length=55, null=True, verbose_name='Kategoriya nomi')),
                ('name_uz', models.CharField(max_length=55, null=True, verbose_name='Kategoriya nomi')),
                ('image', models.ImageField(upload_to='category_images', verbose_name='Kategoriya rasmi')),
                ('products_qty', models.PositiveIntegerField(default=0, verbose_name='Tovarlari soni')),
                ('add_size', models.BooleanField(default=False, verbose_name="Razmer qo'shish")),
                ('add_color', models.BooleanField(default=False, verbose_name="Rang qo'shish")),
            ],
            options={
                'verbose_name': 'Kategoriya',
                'verbose_name_plural': 'Kategoriyalar',
            },
        ),
        migrations.CreateModel(
            name='Colors',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=15, verbose_name='Rang nomi')),
            ],
            options={
                'verbose_name': 'Rang',
                'verbose_name_plural': 'Ranglar',
            },
        ),
        migrations.CreateModel(
            name='SubCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=55, verbose_name='SubKategoriya nomi')),
                ('name_en', models.CharField(max_length=55, null=True, verbose_name='SubKategoriya nomi')),
                ('name_ru', models.CharField(max_length=55, null=True, verbose_name='SubKategoriya nomi')),
                ('name_uz', models.CharField(max_length=55, null=True, verbose_name='SubKategoriya nomi')),
                ('products_qty', models.PositiveIntegerField(default=0, verbose_name='Tovarlari soni')),
                ('category', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='subcategorys', to='main.category', verbose_name='Kategoriyasi')),
            ],
            options={
                'verbose_name': 'SubKategoriya',
                'verbose_name_plural': 'SubKategoriyalar',
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=55, verbose_name='Tovar nomi')),
                ('name_en', models.CharField(max_length=55, null=True, verbose_name='Tovar nomi')),
                ('name_ru', models.CharField(max_length=55, null=True, verbose_name='Tovar nomi')),
                ('name_uz', models.CharField(max_length=55, null=True, verbose_name='Tovar nomi')),
                ('image', models.ImageField(upload_to='category_images', verbose_name='Tovar rasmi')),
                ('qty', models.PositiveIntegerField(default=0, verbose_name='Ombordagi soni')),
                ('description', models.TextField(verbose_name='Tovar xaqida')),
                ('description_en', models.TextField(null=True, verbose_name='Tovar xaqida')),
                ('description_ru', models.TextField(null=True, verbose_name='Tovar xaqida')),
                ('description_uz', models.TextField(null=True, verbose_name='Tovar xaqida')),
                ('rating', models.PositiveIntegerField(default=0, verbose_name='Reyting')),
                ('views', models.PositiveIntegerField(default=0, verbose_name="Ko'rishlar soni")),
                ('size', models.CharField(blank=True, choices=[('xs', 'xs'), ('s', 's'), ('m', 'm'), ('l', 'l'), ('xl', 'xl')], max_length=5, verbose_name='Razmeri')),
                ('price_uzs', models.PositiveIntegerField(default=0, verbose_name='Narxi uzs')),
                ('price_usd', models.DecimalField(decimal_places=2, default=0.0, max_digits=8, verbose_name='Narxi usd')),
                ('price_rub', models.DecimalField(decimal_places=2, default=0.0, max_digits=8, verbose_name='Narxi rub')),
                ('options', ckeditor.fields.RichTextField()),
                ('options_en', ckeditor.fields.RichTextField(null=True)),
                ('options_ru', ckeditor.fields.RichTextField(null=True)),
                ('options_uz', ckeditor.fields.RichTextField(null=True)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='main.category', verbose_name='Kategoriyasi')),
                ('colors', models.ManyToManyField(to='main.colors')),
                ('subcategory', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='main.subcategory', verbose_name='SubKategoriyasi')),
            ],
        ),
    ]
