# Generated by Django 4.0.5 on 2022-07-28 18:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CartProduct',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('qty', models.PositiveIntegerField(default=1)),
                ('total_price', models.PositiveIntegerField(default=0)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cart_products', to='main.product')),
            ],
            options={
                'verbose_name': 'Savatcha tovari',
                'verbose_name_plural': 'Savatcha tovarlari',
            },
        ),
        migrations.CreateModel(
            name='Cart',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('calculated_summa', models.PositiveIntegerField(default=0)),
                ('sale', models.PositiveIntegerField(default=0)),
                ('shipping', models.PositiveIntegerField(default=0)),
                ('total_summa', models.PositiveIntegerField(default=0)),
                ('products', models.ManyToManyField(to='cart.cartproduct')),
            ],
            options={
                'verbose_name': 'Savatcha ',
                'verbose_name_plural': 'Savatchalar',
            },
        ),
    ]
